import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'About HoodScan',
  description: 'HoodScan is an AI-powered blockchain explorer for Robinhood Chain. Track tokens, wallets, and transactions in real-time.',
};

export default function AboutPage() {
  return (
    <div style={{ maxWidth: 800, margin: '0 auto', padding: '3rem 1.5rem' }}>
      <h1 style={{ fontSize: '2rem', fontWeight: 800, marginBottom: '1rem' }}>About HoodScan</h1>
      <p style={{ color: 'var(--muted)', fontSize: '1.1rem', lineHeight: 1.7, marginBottom: '2rem' }}>
        HoodScan is an AI-powered blockchain explorer built for Robinhood Chain — the fastest path to exploring on-chain activity, tokens, and wallets on the network.
      </p>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '1.5rem', marginBottom: '3rem' }}>
        {[
          { icon: '🔍', title: 'Block Explorer', desc: 'Browse every block and transaction confirmed on Robinhood Chain in real time.' },
          { icon: '🪙', title: 'Token Explorer', desc: 'Discover every ERC-20 token deployed on Robinhood Chain with holder and transfer data.' },
          { icon: '👛', title: 'Wallet Tracker', desc: 'Track any wallet address — view balances, token holdings, and full transaction history.' },
          { icon: '🤖', title: 'AI Risk Summary', desc: 'Automatic rule-based risk analysis for every token to help you stay informed.' },
        ].map(({ icon, title, desc }) => (
          <div key={title} style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 12, padding: '1.5rem' }}>
            <div style={{ fontSize: '2rem', marginBottom: '0.75rem' }}>{icon}</div>
            <h3 style={{ fontWeight: 700, fontSize: '1rem', margin: '0 0 0.5rem' }}>{title}</h3>
            <p style={{ color: 'var(--muted)', fontSize: '0.875rem', lineHeight: 1.6, margin: 0 }}>{desc}</p>
          </div>
        ))}
      </div>

      <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 12, padding: '2rem' }}>
        <h2 style={{ fontWeight: 700, fontSize: '1.1rem', marginBottom: '1rem' }}>Data & Disclaimer</h2>
        <p style={{ color: 'var(--muted)', fontSize: '0.875rem', lineHeight: 1.7, margin: '0 0 0.75rem' }}>
          HoodScan indexes data from the Robinhood Chain RPC and Blockscout API. All data is provided for informational purposes only. The AI Risk Summary is generated by automated rules and does not constitute financial advice.
        </p>
        <p style={{ color: 'var(--muted)', fontSize: '0.875rem', lineHeight: 1.7, margin: 0 }}>
          HoodScan is an independent project and is not affiliated with Robinhood Markets, Inc.
        </p>
      </div>
    </div>
  );
}
